# Generated by Django 5.2.7 on 2025-11-10 04:35

import django.core.validators
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.fields
import wagtail.search.index
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailcore', '0095_groupsitepermission'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Location name', max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Show this location in filters')),
            ],
            options={
                'verbose_name': 'Build Location',
                'verbose_name_plural': 'Build Locations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HouseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Category name (e.g., 'Freedom', 'Designer')", max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Category description')),
                ('icon', models.CharField(blank=True, help_text='Icon identifier (optional)', max_length=50)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
            ],
            options={
                'verbose_name': 'House Category',
                'verbose_name_plural': 'House Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HouseDesignsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro_title', models.CharField(default='Home Designs Melbourne', help_text='Page title', max_length=200)),
                ('intro_text', wagtail.fields.RichTextField(blank=True, help_text='Introduction text below title')),
                ('designs_per_page', models.IntegerField(default=12, help_text='Number of designs to show per page', validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'verbose_name': 'House Designs Index Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HouseDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="House design name (e.g., 'Ainstie', 'Aira')", max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', wagtail.fields.RichTextField(blank=True, help_text='Brief description of the house design')),
                ('storeys', models.CharField(choices=[('1', 'Single Storey'), ('2', 'Double Storey'), ('3', 'Three Storey')], default='1', help_text='Number of storeys', max_length=20)),
                ('bedrooms', models.IntegerField(help_text='Number of bedrooms', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('bathrooms', models.DecimalField(decimal_places=1, help_text='Number of bathrooms (e.g., 2.5)', max_digits=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('garage_spaces', models.IntegerField(default=2, help_text='Number of garage/car spaces', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('min_block_width', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum block width in meters', max_digits=5, null=True)),
                ('max_block_width', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum block width in meters (optional)', max_digits=5, null=True)),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, help_text="Base price (leave empty for 'Contact for pricing')", max_digits=12, null=True)),
                ('price_note', models.CharField(blank=True, help_text="Additional pricing info (e.g., 'Plus site costs')", max_length=200)),
                ('is_on_display', models.BooleanField(default=False, help_text="Mark as 'On Display'")),
                ('has_virtual_tour', models.BooleanField(default=False, help_text='Has virtual tour available')),
                ('virtual_tour_url', models.URLField(blank=True, help_text='Virtual tour URL (if available)')),
                ('additional_content', wagtail.fields.StreamField([('content', 30)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Learn More', 'help_text': 'Text displayed on the button', 'max_length': 50}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary (Filled)'), ('secondary', 'Secondary (Outlined)'), ('text', 'Text Only')], 'help_text': 'Visual style of the button'}), 2: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Check if linking to external website', 'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'help_text': 'External URL (if external link is checked)', 'required': False}), 4: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Internal page link (if external link is NOT checked)', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('button_text', 0), ('button_style', 1), ('is_external_link', 2), ('external_url', 3), ('page_link', 4)]], {}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Select an image'}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': 'Alternative text for accessibility', 'max_length': 255, 'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Image caption (optional)', 'max_length': 255, 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('image', 6), ('alt_text', 7), ('caption', 8)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {'label': 'Gallery Images', 'max_num': 20, 'min_num': 1}), 11: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('grid', 'Grid Layout'), ('masonry', 'Masonry Layout'), ('carousel', 'Carousel')], 'help_text': 'Gallery layout style'}), 12: ('wagtail.blocks.StructBlock', [[('images', 10), ('layout', 11)]], {}), 13: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('1', 'Single Storey'), ('2', 'Double Storey'), ('3', 'Three Storey')], 'help_text': 'Number of storeys', 'required': False}), 14: ('wagtail.blocks.IntegerBlock', (), {'help_text': 'Number of bedrooms', 'max_value': 10, 'min_value': 1, 'required': False}), 15: ('wagtail.blocks.DecimalBlock', (), {'decimal_places': 1, 'help_text': 'Number of bathrooms (e.g., 2.5)', 'max_value': 10, 'min_value': 1, 'required': False}), 16: ('wagtail.blocks.IntegerBlock', (), {'help_text': 'Number of garage spaces', 'max_value': 5, 'min_value': 0, 'required': False}), 17: ('wagtail.blocks.DecimalBlock', (), {'decimal_places': 1, 'help_text': 'Minimum block width in meters', 'required': False}), 18: ('wagtail.blocks.DecimalBlock', (), {'decimal_places': 1, 'help_text': 'Maximum block width in meters (optional)', 'required': False}), 19: ('wagtail.blocks.StructBlock', [[('storeys', 13), ('bedrooms', 14), ('bathrooms', 15), ('garage_spaces', 16), ('min_block_width', 17), ('max_block_width', 18)]], {}), 20: ('wagtail.blocks.DecimalBlock', (), {'decimal_places': 2, 'help_text': "Base price (leave empty for 'Contact for pricing')", 'required': False}), 21: ('wagtail.blocks.CharBlock', (), {'default': 'Starting from', 'help_text': "Label before price (e.g., 'Starting from', 'From')", 'max_length': 100}), 22: ('wagtail.blocks.CharBlock', (), {'default': '$', 'help_text': 'Currency symbol', 'max_length': 10}), 23: ('wagtail.blocks.TextBlock', (), {'help_text': 'Additional pricing notes (optional)', 'required': False}), 24: ('wagtail.blocks.StructBlock', [[('base_price', 20), ('price_label', 21), ('currency', 22), ('price_note', 23)]], {}), 25: ('wagtail.blocks.CharBlock', (), {'help_text': "Icon identifier (e.g., 'bed', 'bath', 'garage')", 'max_length': 50, 'required': False}), 26: ('wagtail.blocks.CharBlock', (), {'help_text': "Feature label (e.g., 'Bedrooms')", 'max_length': 50}), 27: ('wagtail.blocks.CharBlock', (), {'help_text': "Feature value (e.g., '4')", 'max_length': 50}), 28: ('wagtail.blocks.StructBlock', [[('icon', 25), ('label', 26), ('value', 27)]], {}), 29: ('wagtail.blocks.ListBlock', (28,), {'icon': 'list-ul', 'label': 'Features List'}), 30: ('wagtail.blocks.StreamBlock', [[('cta_button', 5), ('image', 9), ('image_gallery', 12), ('specifications', 19), ('pricing', 24), ('features_list', 29)]], {})}, default=list, help_text='Additional flexible content blocks')),
                ('is_published', models.BooleanField(default=True, help_text='Show this design on the website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('build_location', models.ForeignKey(blank=True, help_text='Primary build location', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='house_designs', to='house_designs.buildlocation')),
                ('category', models.ForeignKey(blank=True, help_text='House design category (e.g., Freedom, Designer)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='house_designs', to='house_designs.housecategory')),
                ('featured_image', models.ForeignKey(blank=True, help_text='Main display image for cards/listings', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'House Design',
                'verbose_name_plural': 'House Designs',
                'ordering': ['name'],
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='HouseDesignTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='house_designs.housedesign')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='housedesign',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='house_designs.HouseDesignTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
