# Generated by Django 5.2.7 on 2025-11-10 05:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_designs', '0001_initial'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='housedesignsindexpage',
            name='hero_background_image',
            field=models.ForeignKey(blank=True, help_text='Hero section background image (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='housedesignsindexpage',
            name='hero_overlay_opacity',
            field=models.IntegerField(default=50, help_text='Background image overlay darkness (0-100, default 50)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
