# Generated by Django 5.2.7 on 2025-11-10 06:31

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0095_groupsitepermission'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='Shambala Homes', help_text='Site title shown in header if no logo is provided', max_length=250)),
                ('header_cta_text', models.CharField(blank=True, help_text='Call-to-action button text in header (e.g., "Get Started")', max_length=50)),
                ('header_cta_link', models.CharField(blank=True, help_text='Call-to-action button URL', max_length=500)),
                ('footer_tagline', models.CharField(blank=True, help_text='Tagline or slogan displayed in footer', max_length=250)),
                ('footer_description', wagtail.fields.RichTextField(blank=True, help_text='Brief description about the company in footer')),
                ('footer_email', models.EmailField(blank=True, help_text='Contact email displayed in footer', max_length=254)),
                ('footer_phone', models.CharField(blank=True, help_text='Contact phone number displayed in footer', max_length=50)),
                ('footer_address', models.TextField(blank=True, help_text='Physical address displayed in footer')),
                ('facebook_url', models.URLField(blank=True, help_text='Facebook profile URL')),
                ('instagram_url', models.URLField(blank=True, help_text='Instagram profile URL')),
                ('twitter_url', models.URLField(blank=True, help_text='Twitter profile URL')),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn profile URL')),
                ('youtube_url', models.URLField(blank=True, help_text='YouTube channel URL')),
                ('copyright_text', models.CharField(blank=True, default='© 2025 Shambala Homes. All rights reserved.', help_text='Copyright text in footer', max_length=250)),
                ('footer_column_1_title', models.CharField(blank=True, default='Quick Links', help_text='Title for first footer column', max_length=100)),
                ('footer_column_2_title', models.CharField(blank=True, default='Services', help_text='Title for second footer column', max_length=100)),
                ('footer_column_3_title', models.CharField(blank=True, default='Contact', help_text='Title for third footer column', max_length=100)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
                ('site_logo', models.ForeignKey(blank=True, help_text='Logo displayed in header (recommended: SVG or PNG with transparent background)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Site Settings',
            },
        ),
    ]
