# Generated by Django 5.2.7 on 2025-11-10 12:28

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='copyright_text',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='footer_address',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='footer_column_1_title',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='footer_column_2_title',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='footer_column_3_title',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='footer_description',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='footer_email',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='footer_phone',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='footer_tagline',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='header_cta_link',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='header_cta_text',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='site_logo',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='site_title',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_address',
            field=models.TextField(blank=True, help_text='Physical address'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Primary contact email', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Primary contact phone number', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_content',
            field=wagtail.fields.StreamField([('footer_section', 11)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('columns', 'Link Columns'), ('text', 'Text Content'), ('contact', 'Contact Info')], 'help_text': 'Type of footer section'}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': "Column heading (e.g., 'Quick Links')", 'max_length': 100}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 3: ('wagtail.blocks.URLBlock', (), {'help_text': 'External URL', 'required': False}), 4: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Or choose an internal page', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('text', 2), ('link', 3), ('page', 4)]], {}), 6: ('wagtail.blocks.ListBlock', (5,), {}), 7: ('wagtail.blocks.StructBlock', [[('heading', 1), ('links', 6)]], {}), 8: ('wagtail.blocks.ListBlock', (7,), {'help_text': "Add footer columns (for 'Link Columns' type)", 'required': False}), 9: ('wagtail.blocks.RichTextBlock', (), {'help_text': "Rich text content (for 'Text Content' type)", 'required': False}), 10: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('section_type', 0), ('columns', 8), ('content', 9), ('show_email', 10), ('show_phone', 10), ('show_address', 10)]], {})}, help_text='Configure footer sections (columns, links, social media, etc.)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_copyright',
            field=wagtail.fields.RichTextField(blank=True, help_text='Copyright text displayed at the bottom of the footer'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='header_logo_text',
            field=models.CharField(default='SHAMBALA HOMES', help_text='Text to display in the header logo', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='header_menu_items',
            field=wagtail.fields.StreamField([('menu_item', 7)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Menu item text', 'max_length': 100}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Accessibility label', 'max_length': 100}), 2: ('wagtail.blocks.URLBlock', (), {'help_text': 'External URL or leave blank for internal page', 'required': False}), 3: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Or choose an internal page', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 5: ('wagtail.blocks.StructBlock', [[('label', 4), ('link', 2), ('page', 3)]], {}), 6: ('wagtail.blocks.ListBlock', (5,), {'help_text': 'Add sub-menu items', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('label', 0), ('aria_label', 1), ('link', 2), ('page', 3), ('sub_items', 6)]], {})}, help_text='Configure the main navigation menu items'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='twitter_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='youtube_url',
            field=models.URLField(blank=True),
        ),
    ]
