# Generated by Django 5.2.7 on 2025-11-03 08:25

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_hero_image_homepage_intro'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='background_image',
            field=models.ForeignKey(blank=True, help_text='Hero background image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_link',
            field=models.CharField(default='#contact', help_text='Call-to-action link', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_text',
            field=models.CharField(default='Get a Free Site Visit', help_text='Call-to-action button text', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='description',
            field=models.TextField(blank=True, help_text='Hero description text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='main_title_word_1',
            field=models.CharField(default='we', help_text='First word of main title', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='main_title_word_2',
            field=models.CharField(default='make', help_text='Second word of main title', max_length=50),
        ),
        migrations.CreateModel(
            name='ServiceBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_boxes', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TypedText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('text', models.CharField(max_length=200)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='typed_texts', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
