# Generated by Django 5.2.7 on 2025-11-07 09:47

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_background_image_homepage_cta_link_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('hero_section', 14), ('text_section', 19), ('image_gallery', 26), ('services_section', 38), ('testimonials_section', 46), ('cta_section', 52), ('contact_form', 61), ('video_section', 69), ('social_media', 75), ('embed', 76)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Transform your<br/>outdoor dreams', 'help_text': 'Main hero title (supports HTML line breaks)', 'max_length': 200}), 1: ('wagtail.blocks.CharBlock', (), {'default': 'Get a Free Site Visit', 'max_length': 100}), 2: ('wagtail.blocks.URLBlock', (), {'default': '#contact', 'help_text': 'CTA button link'}), 3: ('wagtail.blocks.URLBlock', (), {'help_text': 'Background video URL (mp4 format recommended)', 'required': False}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Fallback background image if no video', 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Slide title', 'max_length': 100}), 6: ('wagtail.blocks.TextBlock', (), {'help_text': 'Optional slide description', 'required': False}), 7: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Slide image (optimized for slider)'}), 8: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'High-resolution image for fullscreen view (optional)', 'required': False}), 9: ('wagtail.blocks.URLBlock', (), {'help_text': "Optional link for 'Read more'", 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('title', 5), ('description', 6), ('image', 7), ('full_image', 8), ('link', 9)]], {}), 11: ('wagtail.blocks.ListBlock', (10,), {'label': 'Slider Images', 'max_num': 6, 'min_num': 1}), 12: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'help_text': 'Enable slider autoplay'}), 13: ('wagtail.blocks.CharBlock', (), {'default': '5000', 'help_text': 'Autoplay delay in milliseconds', 'max_length': 10}), 14: ('wagtail.blocks.StructBlock', [[('hero_title', 0), ('cta_text', 1), ('cta_link', 2), ('background_video', 3), ('background_image', 4), ('slides', 11), ('autoplay_enabled', 12), ('autoplay_delay', 13)]], {}), 15: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': False}), 16: ('wagtail.blocks.RichTextBlock', (), {}), 17: ('wagtail.blocks.CharBlock', (), {'choices': [('left', 'Left'), ('center', 'Center'), ('right', 'Right')], 'default': 'left', 'max_length': 20}), 18: ('wagtail.blocks.CharBlock', (), {'choices': [('white', 'White'), ('light', 'Light Gray'), ('dark', 'Dark'), ('accent', 'Accent Color')], 'default': 'white', 'max_length': 20}), 19: ('wagtail.blocks.StructBlock', [[('title', 15), ('content', 16), ('text_align', 17), ('background_color', 18)]], {}), 20: ('wagtail.blocks.TextBlock', (), {'required': False}), 21: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 22: ('wagtail.blocks.StructBlock', [[('image', 21), ('caption', 15), ('alt_text', 15)]], {}), 23: ('wagtail.blocks.ListBlock', (22,), {'label': 'Gallery Images', 'min_num': 1}), 24: ('wagtail.blocks.CharBlock', (), {'choices': [('grid', 'Grid Layout'), ('masonry', 'Masonry Layout'), ('slider', 'Slider Layout'), ('lightbox', 'Lightbox Grid')], 'default': 'grid', 'max_length': 20}), 25: ('wagtail.blocks.CharBlock', (), {'choices': [('2', '2 Columns'), ('3', '3 Columns'), ('4', '4 Columns')], 'default': '3', 'help_text': 'Grid columns (desktop)', 'max_length': 10}), 26: ('wagtail.blocks.StructBlock', [[('title', 15), ('description', 20), ('images', 23), ('layout', 24), ('columns', 25)]], {}), 27: ('wagtail.blocks.CharBlock', (), {'default': 'Our Services', 'max_length': 200}), 28: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 29: ('wagtail.blocks.TextBlock', (), {}), 30: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 31: ('wagtail.blocks.CharBlock', (), {'help_text': "Icon class or name (e.g., 'landscape', 'design')", 'max_length': 50, 'required': False}), 32: ('wagtail.blocks.URLBlock', (), {'required': False}), 33: ('wagtail.blocks.CharBlock', (), {'default': 'Learn More', 'max_length': 50}), 34: ('wagtail.blocks.StructBlock', [[('title', 28), ('description', 29), ('image', 30), ('icon', 31), ('link', 32), ('link_text', 33)]], {}), 35: ('wagtail.blocks.ListBlock', (34,), {'max_num': 8, 'min_num': 1}), 36: ('wagtail.blocks.CharBlock', (), {'choices': [('grid', 'Grid Layout'), ('cards', 'Card Layout'), ('list', 'List Layout')], 'default': 'grid', 'max_length': 20}), 37: ('wagtail.blocks.CharBlock', (), {'choices': [('white', 'White'), ('light', 'Light Gray'), ('dark', 'Dark'), ('accent', 'Accent Color')], 'default': 'light', 'max_length': 20}), 38: ('wagtail.blocks.StructBlock', [[('title', 27), ('subtitle', 20), ('services', 35), ('layout', 36), ('background_color', 37)]], {}), 39: ('wagtail.blocks.CharBlock', (), {'default': 'What Our Clients Say', 'max_length': 200}), 40: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': False}), 41: ('wagtail.blocks.CharBlock', (), {'choices': [('1', '1 Star'), ('2', '2 Stars'), ('3', '3 Stars'), ('4', '4 Stars'), ('5', '5 Stars')], 'default': '5', 'max_length': 10, 'required': False}), 42: ('wagtail.blocks.StructBlock', [[('quote', 29), ('author_name', 28), ('author_title', 40), ('author_image', 30), ('rating', 41)]], {}), 43: ('wagtail.blocks.ListBlock', (42,), {'max_num': 10, 'min_num': 1}), 44: ('wagtail.blocks.CharBlock', (), {'choices': [('slider', 'Slider'), ('grid', 'Grid'), ('single', 'Single Featured')], 'default': 'slider', 'max_length': 20}), 45: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'help_text': 'Auto-rotate testimonials'}), 46: ('wagtail.blocks.StructBlock', [[('title', 39), ('subtitle', 20), ('testimonials', 43), ('layout', 44), ('autoplay', 45)]], {}), 47: ('wagtail.blocks.CharBlock', (), {'max_length': 200}), 48: ('wagtail.blocks.CharBlock', (), {'default': 'Get Started', 'max_length': 50}), 49: ('wagtail.blocks.URLBlock', (), {}), 50: ('wagtail.blocks.CharBlock', (), {'max_length': 50, 'required': False}), 51: ('wagtail.blocks.CharBlock', (), {'choices': [('accent', 'Accent Color'), ('dark', 'Dark'), ('gradient', 'Gradient')], 'default': 'accent', 'max_length': 20}), 52: ('wagtail.blocks.StructBlock', [[('title', 47), ('subtitle', 20), ('description', 20), ('primary_button_text', 48), ('primary_button_link', 49), ('secondary_button_text', 50), ('secondary_button_link', 32), ('background_image', 30), ('background_color', 51)]], {}), 53: ('wagtail.blocks.CharBlock', (), {'default': 'Contact Us', 'max_length': 200}), 54: ('wagtail.blocks.CharBlock', (), {'choices': [('text', 'Text'), ('email', 'Email'), ('phone', 'Phone'), ('textarea', 'Message'), ('select', 'Dropdown')], 'default': 'text', 'max_length': 20}), 55: ('wagtail.blocks.BooleanBlock', (), {'default': False}), 56: ('wagtail.blocks.TextBlock', (), {'help_text': 'For dropdown fields: one option per line', 'required': False}), 57: ('wagtail.blocks.StructBlock', [[('field_type', 54), ('label', 28), ('placeholder', 15), ('required', 55), ('options', 56)]], {}), 58: ('wagtail.blocks.ListBlock', (57,), {'label': 'Form Fields'}), 59: ('wagtail.blocks.CharBlock', (), {'default': 'Send Message', 'max_length': 50}), 60: ('wagtail.blocks.TextBlock', (), {'default': "Thank you! We'll get back to you soon."}), 61: ('wagtail.blocks.StructBlock', [[('title', 53), ('subtitle', 20), ('form_fields', 58), ('submit_button_text', 59), ('success_message', 60)]], {}), 62: ('wagtail.blocks.URLBlock', (), {'help_text': 'Video URL (YouTube, Vimeo, or direct mp4)'}), 63: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Direct video file upload (alternative to URL)', 'required': False}), 64: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Video thumbnail/poster image', 'required': False}), 65: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Optional text overlay on video', 'required': False}), 66: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Auto-play video'}), 67: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'help_text': 'Mute video by default'}), 68: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Loop video'}), 69: ('wagtail.blocks.StructBlock', [[('title', 15), ('video_url', 62), ('video_file', 63), ('poster_image', 64), ('overlay_content', 65), ('autoplay', 66), ('muted', 67), ('loop', 68)]], {}), 70: ('wagtail.blocks.CharBlock', (), {'default': 'Follow Us', 'max_length': 200}), 71: ('wagtail.blocks.CharBlock', (), {'choices': [('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'Twitter'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('tiktok', 'TikTok')], 'default': 'instagram', 'max_length': 20}), 72: ('wagtail.blocks.StructBlock', [[('platform', 71), ('url', 49), ('username', 40)]], {}), 73: ('wagtail.blocks.ListBlock', (72,), {'label': 'Social Platforms'}), 74: ('wagtail.blocks.CharBlock', (), {'choices': [('icons', 'Icon Grid'), ('cards', 'Platform Cards'), ('feed', 'Social Feed')], 'default': 'icons', 'max_length': 20}), 75: ('wagtail.blocks.StructBlock', [[('title', 70), ('platforms', 73), ('layout', 74)]], {}), 76: ('wagtail.embeds.blocks.EmbedBlock', (), {'label': 'Embed Content'})}, help_text='Main page content using flexible content blocks'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_autoplay_delay',
            field=models.IntegerField(default=5000, help_text='Autoplay delay in milliseconds'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_autoplay_enabled',
            field=models.BooleanField(default=True, help_text='Enable automatic sliding'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_background_image',
            field=models.ForeignKey(blank=True, help_text='Hero background image (used as fallback or primary background)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_background_video',
            field=models.URLField(blank=True, help_text='Background video URL (mp4 format). Leave blank to use image only.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_cta_link',
            field=models.URLField(default='#contact', help_text='CTA button link'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_cta_text',
            field=models.CharField(default='Get a Free Site Visit', help_text='CTA button text', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(default='Transform your<br/>outdoor dreams', help_text='Main hero title (HTML allowed for line breaks)', max_length=200),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='background_image',
            field=models.ForeignKey(blank=True, help_text='[LEGACY] Hero background image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='cta_link',
            field=models.CharField(default='#contact', help_text='[LEGACY] Call-to-action link', max_length=200),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='cta_text',
            field=models.CharField(default='Get a Free Site Visit', help_text='[LEGACY] Call-to-action button text', max_length=100),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='description',
            field=models.TextField(blank=True, help_text='[LEGACY] Hero description text'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_image',
            field=models.ForeignKey(blank=True, help_text='[LEGACY] Hero image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True, help_text='[LEGACY] Rich text intro'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='main_title_word_1',
            field=models.CharField(default='we', help_text='[LEGACY] First word of main title', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='main_title_word_2',
            field=models.CharField(default='make', help_text='[LEGACY] Second word of main title', max_length=50),
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(help_text='Slide title', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional slide description')),
                ('link', models.URLField(blank=True, help_text="Optional link for 'Read more'")),
                ('full_image', models.ForeignKey(blank=True, help_text='High-resolution image for fullscreen view (1920x1080 recommended)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('image', models.ForeignKey(help_text='Slide image (400x300 recommended for slider)', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_slides', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
    ]
