# Generated by Django 5.2.7 on 2025-11-08 09:33

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_homepage_body_alter_homepage_hero_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('horizontal_slider', 14)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Our Services', 'help_text': 'Section title', 'max_length': 200}), 1: ('wagtail.blocks.TextBlock', (), {'help_text': 'Section description', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'default': '1', 'help_text': 'Display order (1, 2, 3, etc.)', 'max_length': 3}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Slide title', 'max_length': 200}), 4: ('wagtail.blocks.TextBlock', (), {'help_text': 'Slide description', 'required': False}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Slide image'}), 6: ('wagtail.blocks.CharBlock', (), {'default': 'Learn More', 'help_text': 'Text for the slide button', 'max_length': 50}), 7: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Check if this links to an external website', 'required': False}), 8: ('wagtail.blocks.URLBlock', (), {'help_text': "External URL (only used if 'External Link' is checked)", 'required': False}), 9: ('wagtail.blocks.PageChooserBlock', (), {'help_text': "Internal page to link to (only used if 'External Link' is NOT checked)", 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('order', 2), ('title', 3), ('description', 4), ('image', 5), ('button_text', 6), ('is_external_link', 7), ('external_url', 8), ('page_link', 9)]], {}), 11: ('wagtail.blocks.ListBlock', (10,), {'label': 'Slides', 'max_num': 10, 'min_num': 1}), 12: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'help_text': 'Enable slider autoplay'}), 13: ('wagtail.blocks.CharBlock', (), {'default': '3000', 'help_text': 'Autoplay delay in milliseconds', 'max_length': 10}), 14: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('slides', 11), ('autoplay_enabled', 12), ('autoplay_delay', 13)]], {})}, default=list, help_text='Main page content using flexible blocks'),
        ),
    ]
